############################
#
#       Lulu scraper
#
#            by
# 
#     Code Monkey King
#
############################

############################
#
#  Just paste this file's 
# content into scrapy shell
#
############################

# write emty file with column names
import json, csv; open('lulu.csv', 'w').write('title,price,thumbnail_url,image_url,DP Type,Brand,Content,Type\n')

# fetch categories (just append new categories below via copy-pasting line & changing URL)
(fetch('https://www.luluhypermarket.in/en-in/fruits-vegetables-frozen-food-food-cupboard-grocery/c/HY00215074'), [(fetch('https://www.luluhypermarket.in' + url), [csv.DictWriter(open('lulu.csv', 'a'), ['title', 'price', 'thumbnail_url', 'image_url', 'DP Type', 'Brand', 'Content', 'Type']).writerow({'title': response.css('h1[class="pdp-productname"]::text').get(), 'price': 'INR ' + response.css('div[class="prod-price"]').css('span::text').get(), 'thumbnail_url': 'https://www.luluhypermarket.in' + response.css('span[class="thumbnail"]').css('img::attr(src)').get(), 'image_url': 'https://www.luluhypermarket.in' + response.css('div[class="item active"]').css('img::attr(src)').get(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[0]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[0].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[1]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[1].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[-2]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[-2].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[-1]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[-1].strip()}) for index in range(0, 1) if len(response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()) > 1]) for url in response.css('a[class="js-gtm-product-link"]::attr(href)').getall()])
(fetch('https://www.luluhypermarket.in/en-in/fruits-vegetables-fresh-food/c/HY00216202'), [(fetch('https://www.luluhypermarket.in' + url), [csv.DictWriter(open('lulu.csv', 'a'), ['title', 'price', 'thumbnail_url', 'image_url', 'DP Type', 'Brand', 'Content', 'Type']).writerow({'title': response.css('h1[class="pdp-productname"]::text').get(), 'price': 'INR ' + response.css('div[class="prod-price"]').css('span::text').get(), 'thumbnail_url': 'https://www.luluhypermarket.in' + response.css('span[class="thumbnail"]').css('img::attr(src)').get(), 'image_url': 'https://www.luluhypermarket.in' + response.css('div[class="item active"]').css('img::attr(src)').get(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[0]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[0].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[1]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[1].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[-2]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[-2].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[-1]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[-1].strip()}) for index in range(0, 1) if len(response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()) > 1]) for url in response.css('a[class="js-gtm-product-link"]::attr(href)').getall()])
(fetch('https://www.luluhypermarket.in/en-in/rice-pasta-noodles-food-cupboard-grocery/c/HY00214987'), [(fetch('https://www.luluhypermarket.in' + url), [csv.DictWriter(open('lulu.csv', 'a'), ['title', 'price', 'thumbnail_url', 'image_url', 'DP Type', 'Brand', 'Content', 'Type']).writerow({'title': response.css('h1[class="pdp-productname"]::text').get(), 'price': 'INR ' + response.css('div[class="prod-price"]').css('span::text').get(), 'thumbnail_url': 'https://www.luluhypermarket.in' + response.css('span[class="thumbnail"]').css('img::attr(src)').get(), 'image_url': 'https://www.luluhypermarket.in' + response.css('div[class="item active"]').css('img::attr(src)').get(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[0]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[0].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[1]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[1].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[-2]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[-2].strip(), response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()[-1]: response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-7 col-xs-6"]::text').getall()[-1].strip()}) for index in range(0, 1) if len(response.css('div[class="features-ul"]').css('p[class="col-md-5 col-sm-5 col-xs-6"]::text').getall()) > 1]) for url in response.css('a[class="js-gtm-product-link"]::attr(href)').getall()])

